version: '3.1'
services:
  db:
    image: mariadb:10.6
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: qwer4321
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - mariadb-data-volume:/var/lib/mysql
      - ./docker/db:/docker-entrypoint-initdb.d
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: bash -c "irb"
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
      - ~/.ssh:/root/.ssh:ro
      - bundle-volume:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db

#Volumes
volumes:
  bundle-volume:
  mariadb-data-volume:
